<a href="https://colab.research.google.com/github/humayun-mhk/Scikit-learn/blob/main/Logistic_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Logistic Regression:


In [10]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

x = np.arange(10).reshape(10,1)
y = np.array([0,1,0,0,1,1,1,1,0,1])
print(x)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 0 0 1 1 1 1 0 1]


In [12]:
model = LogisticRegression(solver = "liblinear", C=10.0, random_state=0)
model.fit(x,y)
print(model.intercept_)
print(model.coef_)

[-0.66368133]
[[0.25626183]]


In [15]:
p_pred = model.predict_proba(x)
y_pred = model.predict(x)
print(p_pred)
print(y_pred)

[[0.66008686 0.33991314]
 [0.60046896 0.39953104]
 [0.53771763 0.46228237]
 [0.47374812 0.52625188]
 [0.41062894 0.58937106]
 [0.35032116 0.64967884]
 [0.29444559 0.70555441]
 [0.24413314 0.75586686]
 [0.19998097 0.80001903]
 [0.16210138 0.83789862]]
[0 0 0 1 1 1 1 1 1 1]


In [17]:
score = model.score(x,y)
print(score)

0.7


In [18]:
conf = confusion_matrix(y,y_pred)
print(conf)

[[2 2]
 [1 5]]


In [19]:
report = classification_report(y,y_pred)
print(report)

              precision    recall  f1-score   support

           0       0.67      0.50      0.57         4
           1       0.71      0.83      0.77         6

    accuracy                           0.70        10
   macro avg       0.69      0.67      0.67        10
weighted avg       0.70      0.70      0.69        10

