<a href="https://colab.research.google.com/github/humayun-mhk/Scikit-learn/blob/main/MultiClass%20Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

SVM

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import f1_score, jaccard_score, confusion_matrix, classification_report

# Step 1: Load the dataset
path = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/cell_samples.csv"
df = pd.read_csv(path)
data = pd.DataFrame(df)

# Step 2: Simulate a multiclass problem
np.random.seed(4)
data['Class'] = np.random.randint(0, 3, size=len(data))  # Randomly assign classes 0, 1, 2

# Step 3: Prepare the data
X = data[['Clump', 'UnifSize']]  # Features
y = data['Class']  # Target (multiclass)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=4)

print('Train set:', X_train.shape, y_train.shape)
print('Test set:', X_test.shape, y_test.shape)

# Step 4: Train an SVM model
clf = svm.SVC(kernel='rbf')
clf.fit(X_train, y_train)

# Step 5: Make predictions
yhat = clf.predict(X_test)

# Step 6: Evaluate the model
f1 = f1_score(y_test, yhat, average='weighted')
print('F1 Score (Weighted):', f1)

jaccard = jaccard_score(y_test, yhat, average='macro')
print('Jaccard Index (Macro):', jaccard)

conf_matrix = confusion_matrix(y_test, yhat)
print('Confusion Matrix:\n', conf_matrix)

class_report = classification_report(y_test, yhat)
print('Classification Report:\n', class_report)

Train set: (559, 2) (559,)
Test set: (140, 2) (140,)
F1 Score (Weighted): 0.31542518646802986
Jaccard Index (Macro): 0.18792615679693117
Confusion Matrix:
 [[16 30  2]
 [19 25  4]
 [19 19  6]]
Classification Report:
               precision    recall  f1-score   support

           0       0.30      0.33      0.31        48
           1       0.34      0.52      0.41        48
           2       0.50      0.14      0.21        44

    accuracy                           0.34       140
   macro avg       0.38      0.33      0.31       140
weighted avg       0.37      0.34      0.32       140

